### ISSUE TITLE
Tracking Issue for `v0.9`

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#64]
This is a tracking issue for work on `v0.9`.

**Comment by ripytide** [comment]
Okay, I've finished trawling through every issue both closed and open in the issue tracker and itemizing the actionable improvements I agree with in the tracking list above. Some improvements didn't yet have their own issues (particularly many of the points brought up in #39) so I opened some new ones for them. There were also some new improvements I came with, such as #65 and #66, not previously discussed as far as I am aware.

What do you think @kornelski? Specifically it would be useful to me if you'd state which of the listed improvements you'd accept or reject so I don't have to spend time implementing things you'd reject.

**Comment by kornelski** [comment]
### Approvals [WIP]
- [x] #63
- [ ] #14
- [ ] #21
- [ ] #25
- [ ] #46
- [ ] #65 
- [ ] #66
- [ ] #67
- [ ] #68
- [ ] #69
- [ ] #70
- [ ] #72
- [ ] #73

**Comment by ripytide** [comment]
I've decided that I'll be shifting my focus from working on a `0.9` of this crate to creating a new crate due to the decision that this crate will not making any semver-trick incompatible changes. See #83 and #84 for more discussion on this issue.

I'll leave this tracking issue open in case anyone else wants to pickup where I left off.

**Comment by ripytide** [comment]
After more discussion in #85 I am now happy to continue development on `v0.9`, I did make a crate called [pixeli](https://docs.rs/pixeli) but I'll deprecate that now for this crate.

**Comment by kornelski** [comment]
Great. Thanks.

**Comment by kornelski** [comment]
* [ ] Bring back `fn new()` for sensible-order RGB types. The type literal requires a lot of shift-pressing.
* [ ] Aliases for RGB8/RGB16. Type hints are repetitive, and other forms require turbofish.
* [ ] Convenience methods for bytemuck? `slice.as_rgba()` vs `bytemuck::cast_slice::<Rgba<u8>>(slice)`.
* [ ] Add `prelude::*`? There's a bunch of traits.

**Comment by ripytide** [comment]
I'm not sure if this issue is useful anymore

**Comment by rursprung** [comment]
@ripytide & @kornelski: is there any news on the upcoming v0.9? this issue is closed but it hasn't been released yet
also: is there a description of the gap between v0.9 and an upcoming v1.0 (i.e.: why is this still 0.x / what's missing for 1.0?)

thanks for all your work on this so far!

**Comment by ripytide** [comment]
@rursprung long time no see!

See #131 and the `README.md` for our most up to date plan. But in short I think we are waiting to release `v0.8.90` which has all the new stuff to allow people to try out the alphas of that version to gather feedback.

For example, about a month ago I attempted to integrate the new version of `rgb` into a project I'm working on and in the process found some issues that bothered me: #136 #135. Since such changes are infinitely harder to make after making a full release I think it is worth taking the time now to get things sorted.

Perhaps a good metric would be no breaking changes made in 3 months?
